replicas: 3
celeryReplicas: 3
username: {{helmbroker.username}}
password: {{helmbroker.password}}

persistence:
  size: 20Gi
  storageClass: drycc-storage

repositories:
- name: drycc-helm-broker
  url: https://drycc-mirrors.drycc.cc/drycc-addons/addons/releases/download/latest/index.yaml

rabbitmq:
  replicas: 3
  username: drycc
  password: {{64|random_ascii}}
  persistence:
    enabled: true # Set to true to enable persistence
    size: 5Gi # PVC size
    storageClass: "topolvm-ssd"

global:
  rabbitmqLocation: on-cluster
  ingressClass: {{global.ingressClass}}
  clusterDomain: {{global.clusterDomain}}
  platformDomain: {{helmbroker.platformDomain}}
  certManagerEnabled: {{global.certManagerEnabled}}