replicas: 3
celeryReplicas: 3
username: {{helmbroker.username}}
password: {{helmbroker.password}}

persistence:
  size: 20Gi
  storageClass: drycc-storage

repositories:
- name: drycc-helm-broker
  url: https://drycc-mirrors.drycc.cc/drycc-addons/addons/releases/download/latest/index.yaml

rabbitmq:
  replicas: 3
  username: drycc
  password: {{64|random_ascii}}
  persistence:
    enabled: true # Set to true to enable persistence
    size: 5Gi # PVC size
    storageClass: "topolvm-ssd"

acme:
  server: {{acme.server}}
  externalAccountBinding:
    keyID: {{acme.externalAccountBinding.keyID}}
    keySecret: {{acme.externalAccountBinding.keySecret}}

global:
  email: {{global.email}}
  rabbitmqLocation: on-cluster
  gatewayClass: {{global.gatewayClass}}
  clusterDomain: {{global.clusterDomain}}
  platformDomain: {{global.platformDomain}}
  certManagerEnabled: {{global.certManagerEnabled}}