apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  finalizers:
  - kubernetes-incubator/service-catalog
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    heritage: Helm
  name: helmbroker
spec:
  relistBehavior: Duration
  relistRequests: 5
  {%- if global.certManagerEnabled == "true" %}
  url: "https://{{helmbroker.username}}:{{helmbroker.password}}@drycc-helmbroker.{{global.platformDomain}}"
  {%- else %}
  url: "http://{{helmbroker.username}}:{{helmbroker.password}}@drycc-helmbroker.{{global.platformDomain}}"
  {%- endif %}
