
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public
spec:
  addresses:
  - 43.154.180.247/32
  - 43.154.134.79/32
  - 43.159.195.254/32
  serviceAllocation:
    priority: 50
    namespaces:
    - drycc
    - drycc-manager

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
spec:
  addresses:
  - 192.168.11.0/24

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: drycc-l2-advertisement
spec:
  ipAddressPools:
  - public
  - default
