kind: ConfigMap
apiVersion: v1
metadata:
  name: carina-csi-driver-csi-config
  namespace: carina
data:
  config.json: |-
    {
       "diskSelector": [
        {
          "name": "lvmvg-hdd",
          "re": ["sd+"],
          "policy": "LVM",
          "nodeLabel": "drycc.cc/carina-node"
        },
        {
          "name": "lvmvg-nvme",
          "re": ["nvme+"],
          "policy": "LVM",
          "nodeLabel": "drycc.cc/carina-node"
        }
      ],
      "diskScanInterval": "300",
      "schedulerStrategy": "spradout"
    }
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    meta.helm.sh/release-name: carina-csi-driver
    meta.helm.sh/release-namespace: carina
  labels:
    app.kubernetes.io/managed-by: Helm
  name: csi-carina-nvme
parameters:
  carina.storage.io/disk-group-name: lvmvg-nvme
  csi.storage.k8s.io/fstype: xfs
provisioner: carina.storage.io
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    meta.helm.sh/release-name: carina-csi-driver
    meta.helm.sh/release-namespace: carina
  labels:
    app.kubernetes.io/managed-by: Helm
  name: csi-carina-hdd
parameters:
  carina.storage.io/disk-group-name: lvmvg-hdd
  csi.storage.k8s.io/fstype: xfs
provisioner: carina.storage.io
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer